# Generated by Django 2.1.3 on 2019-01-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomCurso', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigoMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
