# Generated by Django 2.1.5 on 2019-01-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('idCurso', models.AutoField(primary_key=True, serialize=False)),
                ('nomCurso', models.CharField(max_length=100)),
                ('objetivo', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=50)),
                ('totalHrs', models.IntegerField()),
                ('horaDiurno', models.CharField(max_length=20)),
                ('horaVespertino', models.CharField(max_length=20)),
                ('certificacion', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('valor', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='staticImg')),
            ],
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('codigoMensaje', models.AutoField(primary_key=True, serialize=False)),
                ('curso', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=30)),
                ('correo', models.EmailField(max_length=30)),
                ('mensaje', models.TextField()),
            ],
        ),
    ]
